[tool.poetry]
name = "replifactory"
version = "7.0.0"
description = "replifactory morbidostat python package"
authors = ["Catalin Rusnac <ctlnrsnc@gmail.com>"]
maintainers = [
    "Fedor Gagarin <fddgagarin@gmail.com>",
]
readme = "README.md"
homepage = "https://replifactory.com"
packages = [
    { include = "**/*.py", from = "flask_app" },
]

[tool.poetry.dependencies]
python = ">=3.9.0, <3.12"
blinker = "^1.6.2"
click = "^8.1.3"
colorama = "^0.4.6"
flask_cors = "*"
flask_sqlalchemy = "*"
flask-static-digest = "^0.4.0"
gspread = "*"
itsdangerous = "^2.1.2"
jinja2 = "^3.1.2"
markupsafe = "^2.1.2"
matplotlib = "*"
numpy = "*"
oauth2client = "*"
pandas = "*"
plotly = "*"
pydantic = "^2.4.0"
pyftdi = "^0.54.0"
pyserial = "^3.5"
pyusb = "^1.2.1"
PyYAML = "^6.0"
schedule = "*"
scipy = "*"
setuptools = "^58.0.4"
six = "^1.16.0"
waitress = "*"
Werkzeug = "^2.3.4"
zipp = "^3.15.0"

[tool.poetry.extras]
replifactory = ["python-pxushover", "python-telegram-bot"]

[tool.poetry.group.dev.dependencies]
autopep8 = "^2.0.1"
black = "^23.3.0"
flake8 = "^6.0.0"
isort = "^5.12.0"
pytest = "^7.2.1"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
pythonpath = "flask_app"
addopts = [
    "--import-mode=importlib",
    "--cov=replifactory",
    "--cov-report=xml",
    "--cov-report=term",
]
filterwarnings = [
    # note the use of single quote below to denote "raw" strings in TOML
    'ignore::DeprecationWarning:jupyter_client.*:',
]

[tool.isort]
profile = "black"
src_paths = ["flask_app", "tests"]